[package]
name = "disco_boy"
version = "0.1.0"
authors = ["narwhaldisco <nward24@uwo.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
